export const SIDEBAR_WIDTH = 272;
export const COLOR_PALETTE_SIZE = 4096;
export const HUE_GOLDEN_ANGLE = 137.508;
export const DEFAULT_BG_OPACITY = [0.6, 1];
export const DEFAULT_BG_SIZE = [0.7, 1];
export const LASSO_DIM_OPACITY = [0.15, 1];
export const LASSO_DIM_SIZE = [0.5, 1];
export const LASSO_BG_COLOR = "#555";
export const DEFAULT_BG_COLOR = "gray";
